name: Test and Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential lcov
        
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug --target tests
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ./tests
        ctest --output-on-failure
        
    - name: Generate Coverage
      working-directory: ${{github.workspace}}/build
      run: |
        lcov --directory . --capture --output-file coverage.info --ignore-errors mismatch
        lcov --remove coverage.info '*/third-party/*' '*/tests/*' '/usr/*' --output-file coverage.info
        lcov --list coverage.info
        
    - name: Upload Coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: ${{github.workspace}}/build/coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }}